### ISSUE TITLE
Binary Incompability in 0.0.10

### ISSUE THREAD

**Issue by GlassAndOneHalf** [tpolecat/natchez#101]
Whilst upgrading Natchez from 0.0.8 to 0.0.10 I stumbled across this binary incompatibility introduced by the `lightstep-grpc` project, specifically caused by an import in the `GrpcCollectorClientProvider` class.

```
java.util.ServiceConfigurationError: com.lightstep.tracer.shared.CollectorClientProvider: Provider com.lightstep.tracer.shared.GrpcCollectorClientProvider could not be instantiated
  at java.util.ServiceLoader.fail(ServiceLoader.java:232)
  at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
  at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
  at java.util.ServiceLoader$LazyIterator.access$700(ServiceLoader.java:323)
  at java.util.ServiceLoader$LazyIterator$2.run(ServiceLoader.java:407)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:409)
  at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
  at com.lightstep.tracer.shared.CollectorClientProvider.load(CollectorClientProvider.java:42)
  at com.lightstep.tracer.shared.CollectorClientProvider.<clinit>(CollectorClientProvider.java:19)
  at com.lightstep.tracer.shared.AbstractTracer.<init>(AbstractTracer.java:157)
  at com.lightstep.tracer.jre.JRETracer.<init>(JRETracer.java:31)
      ...
Caused by: java.lang.NoClassDefFoundError: io/grpc/util/RoundRobinLoadBalancerFactory
  at java.lang.Class.getDeclaredConstructors0(Native Method)
  at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
  at java.lang.Class.getConstructor0(Class.java:3075)
  at java.lang.Class.newInstance(Class.java:412)
  at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
  ... 42 more
Caused by: java.lang.ClassNotFoundException: io.grpc.util.RoundRobinLoadBalancerFactory
  at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  at sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:98)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
```

Publishing a local version of `natchez` from master seems to resolve the issue as the problematic dependency has been updated to address the binary incompability. Would it be possible to cut a new release that uses the latest dependencies?

**Comment by tpolecat** [comment]
Yeah these Java libraries change almost daily, in unpredictable ways, and it's hard to keep up. I'll merge everything and tag a release. Until then you can grab a snapshot.

**Comment by GlassAndOneHalf** [comment]
Very much appreciated! Thanks! 🍻
